name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install and Build Frontend
      working-directory: ./frontend
      run: |
        node -v
        npm install
        npm run build

    - name: Upload Frontend Artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: frontend/dist

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create bin and Compile
      run: |
        mkdir -p bin
        javac -cp "lib/*" -d bin src/com/jobportal/application/*.java src/com/jobportal/application/models/*.java

    - name: Package JAR
      run: |
        cd bin
        jar -cvf ../HireNova-Backend.jar .
        
    - name: Upload Backend Artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-jar
        path: HireNova-Backend.jar
